// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TradingAssistant.Infrastructure.Persistence;

#nullable disable

namespace TradingAssistant.Infrastructure.Migrations.Backtest
{
    [DbContext(typeof(BacktestDbContext))]
    [Migration("20260225225928_InitialBacktest")]
    partial class InitialBacktest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TradingAssistant.Domain.Backtesting.BacktestResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BacktestRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MaxDrawdown")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("ResultData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SharpeRatio")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal>("TotalReturn")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("TotalTrades")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("WinRate")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.HasKey("Id");

                    b.HasIndex("BacktestRunId")
                        .IsUnique();

                    b.ToTable("BacktestResults");
                });

            modelBuilder.Entity("TradingAssistant.Domain.Backtesting.BacktestRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("StrategyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId");

                    b.ToTable("BacktestRuns");
                });

            modelBuilder.Entity("TradingAssistant.Domain.Backtesting.Strategy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Strategies");
                });

            modelBuilder.Entity("TradingAssistant.Domain.Backtesting.StrategyRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IndicatorType")
                        .HasColumnType("integer");

                    b.Property<int>("SignalType")
                        .HasColumnType("integer");

                    b.Property<Guid>("StrategyId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Threshold")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId");

                    b.ToTable("StrategyRules");
                });

            modelBuilder.Entity("TradingAssistant.Domain.Backtesting.BacktestResult", b =>
                {
                    b.HasOne("TradingAssistant.Domain.Backtesting.BacktestRun", "BacktestRun")
                        .WithOne("Result")
                        .HasForeignKey("TradingAssistant.Domain.Backtesting.BacktestResult", "BacktestRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BacktestRun");
                });

            modelBuilder.Entity("TradingAssistant.Domain.Backtesting.BacktestRun", b =>
                {
                    b.HasOne("TradingAssistant.Domain.Backtesting.Strategy", "Strategy")
                        .WithMany("BacktestRuns")
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Strategy");
                });

            modelBuilder.Entity("TradingAssistant.Domain.Backtesting.StrategyRule", b =>
                {
                    b.HasOne("TradingAssistant.Domain.Backtesting.Strategy", "Strategy")
                        .WithMany("Rules")
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Strategy");
                });

            modelBuilder.Entity("TradingAssistant.Domain.Backtesting.BacktestRun", b =>
                {
                    b.Navigation("Result");
                });

            modelBuilder.Entity("TradingAssistant.Domain.Backtesting.Strategy", b =>
                {
                    b.Navigation("BacktestRuns");

                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
