// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingAssistant.Infrastructure.Persistence;

#nullable disable

namespace TradingAssistant.Infrastructure.Persistence.Migrations.Intelligence
{
    [DbContext(typeof(IntelligenceDbContext))]
    [Migration("20260303180254_AddRuleDiscovery")]
    partial class AddRuleDiscovery
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("TradingAssistant.Domain.Intelligence.BreadthSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AdvanceDeclineRatio")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("Advancing")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Declining")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("NewHighs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NewLows")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PctAbove200Sma")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PctAbove50Sma")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalStocks")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MarketCode", "SnapshotDate");

                    b.ToTable("BreadthSnapshots");
                });

            modelBuilder.Entity("TradingAssistant.Domain.Intelligence.CircuitBreakerEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentEquity")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeactivationReason")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DrawdownPercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("OpenPositionsAtEvent")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PeakEquity")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("PendingOrdersCancelled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegimeAtEvent")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RegimeConfidence")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ThresholdPercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "EventDate");

                    b.ToTable("CircuitBreakerEvents");
                });

            modelBuilder.Entity("TradingAssistant.Domain.Intelligence.CorrelationSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LookbackDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatrixJson")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotDate");

                    b.ToTable("CorrelationSnapshots");
                });

            modelBuilder.Entity("TradingAssistant.Domain.Intelligence.CostProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CommissionPerShare")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CommissionPercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExchangeFeePercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SpreadEstimatePercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxPercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MarketCode", "IsActive");

                    b.ToTable("CostProfiles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2c3d4e5-0001-0001-0001-000000000001"),
                            CommissionPerShare = 0.005m,
                            CommissionPercent = 0m,
                            CreatedAt = new DateTime(2026, 3, 3, 18, 2, 54, 74, DateTimeKind.Utc).AddTicks(4494),
                            ExchangeFeePercent = 0m,
                            IsActive = true,
                            MarketCode = "US_SP500",
                            Name = "US Equities (default)",
                            SpreadEstimatePercent = 0.1m,
                            TaxPercent = 0m
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-0001-0001-0001-000000000002"),
                            CommissionPerShare = 0m,
                            CommissionPercent = 0.03m,
                            CreatedAt = new DateTime(2026, 3, 3, 18, 2, 54, 74, DateTimeKind.Utc).AddTicks(4518),
                            ExchangeFeePercent = 0m,
                            IsActive = true,
                            MarketCode = "IN_NIFTY50",
                            Name = "India Equities (default)",
                            SpreadEstimatePercent = 0.05m,
                            TaxPercent = 0.025m
                        });
                });

            modelBuilder.Entity("TradingAssistant.Domain.Intelligence.MarketProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("DnaProfileJson")
                        .IsRequired()
                        .HasMaxLength(16000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DnaProfileUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VixSymbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MarketCode")
                        .IsUnique();

                    b.ToTable("MarketProfiles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            ConfigJson = "{\"tradingHours\":{\"open\":\"09:30\",\"close\":\"16:00\"},\"regimeThresholds\":{\"highVol\":30,\"bullBreadth\":0.60,\"bearBreadth\":0.40}}",
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            DataSource = "yahoo",
                            DnaProfileJson = "{}",
                            Exchange = "NYSE/NASDAQ",
                            IsActive = true,
                            MarketCode = "US_SP500",
                            Timezone = "America/New_York",
                            VixSymbol = "^VIX"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            ConfigJson = "{\"tradingHours\":{\"open\":\"09:15\",\"close\":\"15:30\"},\"regimeThresholds\":{\"highVol\":25,\"bullBreadth\":0.55,\"bearBreadth\":0.45}}",
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "INR",
                            DataSource = "yahoo",
                            DnaProfileJson = "{}",
                            Exchange = "NSE",
                            IsActive = true,
                            MarketCode = "IN_NIFTY50",
                            Timezone = "Asia/Kolkata",
                            VixSymbol = "^INDIAVIX"
                        });
                });

            modelBuilder.Entity("TradingAssistant.Domain.Intelligence.MarketRegime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AdvanceDeclineRatio")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BreadthScore")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ClassifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ConfidenceScore")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentRegime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PctAbove200Sma")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("RegimeDuration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegimeStartDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SmaSlope200")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SmaSlope50")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VixLevel")
                        .HasPrecision(8, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClassifiedAt");

                    b.HasIndex("MarketCode");

                    b.ToTable("MarketRegimes");
                });

            modelBuilder.Entity("TradingAssistant.Domain.Intelligence.PipelineRunLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RunDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("StepOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MarketCode", "RunDate");

                    b.ToTable("PipelineRunLogs");
                });

            modelBuilder.Entity("TradingAssistant.Domain.Intelligence.RegimeTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BreadthScore")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FromRegime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PctAbove200Sma")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SmaSlope200")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SmaSlope50")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<int>("ToRegime")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TransitionDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VixLevel")
                        .HasPrecision(8, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MarketCode");

                    b.HasIndex("TransitionDate");

                    b.ToTable("RegimeTransitions");
                });

            modelBuilder.Entity("TradingAssistant.Domain.Intelligence.RuleDiscovery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscoveredRulesJson")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LosingTrades")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("PatternsJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StrategyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("TradeCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("WinningTrades")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MarketCode");

                    b.HasIndex("StrategyId");

                    b.ToTable("RuleDiscoveries");
                });

            modelBuilder.Entity("TradingAssistant.Domain.Intelligence.StrategyAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AllocationPercent")
                        .HasPrecision(8, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("Regime")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StrategyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SwitchoverStartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MarketCode")
                        .IsUnique();

                    b.ToTable("StrategyAssignments");
                });

            modelBuilder.Entity("TradingAssistant.Domain.Intelligence.StrategyAutopsy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketConditionImpact")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaxDrawdownPercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MonthlyReturnPercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("PrimaryLossReason")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecommendationsJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RootCausesJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SharpeRatio")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShouldRetire")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StrategyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("TradeCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WinRate")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId");

                    b.HasIndex("MarketCode", "PeriodStart");

                    b.ToTable("StrategyAutopsies");
                });

            modelBuilder.Entity("TradingAssistant.Domain.Intelligence.StrategyRegimeScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("Regime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SampleSize")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SharpeRatio")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StrategyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId", "MarketCode", "Regime")
                        .IsUnique();

                    b.ToTable("StrategyRegimeScores");
                });

            modelBuilder.Entity("TradingAssistant.Domain.Intelligence.TournamentEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AllocationPercent")
                        .HasPrecision(8, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DaysActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaxDrawdown")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PaperAccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PromotedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RetiredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RetirementReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SharpeRatio")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StrategyId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalReturn")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalTrades")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TournamentRunId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WinRate")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId");

                    b.HasIndex("Status", "MarketCode");

                    b.ToTable("TournamentEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
