// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingAssistant.Infrastructure.Persistence;

#nullable disable

namespace TradingAssistant.Infrastructure.Persistence.Migrations.Intelligence
{
    [DbContext(typeof(IntelligenceDbContext))]
    [Migration("20260303190000_AddMlAndFeedbackTables")]
    partial class AddMlAndFeedbackTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("TradingAssistant.Domain.Intelligence.BreadthSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AdvanceDeclineRatio")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("Advancing")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Declining")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("NewHighs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NewLows")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PctAbove200Sma")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PctAbove50Sma")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalStocks")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MarketCode", "SnapshotDate");

                    b.ToTable("BreadthSnapshots");
                });

            modelBuilder.Entity("TradingAssistant.Domain.Intelligence.CircuitBreakerEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentEquity")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeactivationReason")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DrawdownPercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("OpenPositionsAtEvent")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PeakEquity")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("PendingOrdersCancelled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegimeAtEvent")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RegimeConfidence")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ThresholdPercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "EventDate");

                    b.ToTable("CircuitBreakerEvents");
                });

            modelBuilder.Entity("TradingAssistant.Domain.Intelligence.CorrelationSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LookbackDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatrixJson")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotDate");

                    b.ToTable("CorrelationSnapshots");
                });

            modelBuilder.Entity("TradingAssistant.Domain.Intelligence.CostProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CommissionPerShare")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CommissionPercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExchangeFeePercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SpreadEstimatePercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxPercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MarketCode", "IsActive");

                    b.ToTable("CostProfiles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2c3d4e5-0001-0001-0001-000000000001"),
                            CommissionPerShare = 0.005m,
                            CommissionPercent = 0m,
                            CreatedAt = new DateTime(2026, 3, 3, 18, 28, 43, 285, DateTimeKind.Utc).AddTicks(4420),
                            ExchangeFeePercent = 0m,
                            IsActive = true,
                            MarketCode = "US_SP500",
                            Name = "US Equities (default)",
                            SpreadEstimatePercent = 0.1m,
                            TaxPercent = 0m
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-0001-0001-0001-000000000002"),
                            CommissionPerShare = 0m,
                            CommissionPercent = 0.03m,
                            CreatedAt = new DateTime(2026, 3, 3, 18, 28, 43, 285, DateTimeKind.Utc).AddTicks(4429),
                            ExchangeFeePercent = 0m,
                            IsActive = true,
                            MarketCode = "IN_NIFTY50",
                            Name = "India Equities (default)",
                            SpreadEstimatePercent = 0.05m,
                            TaxPercent = 0.025m
                        });
                });

            modelBuilder.Entity("TradingAssistant.Domain.Intelligence.EnsembleSignal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AgreeingVoters")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("MinAgreement")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SignalDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalVoters")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VotesJson")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("VotingMode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SignalDate");

                    b.HasIndex("MarketCode", "Symbol", "SignalDate");

                    b.ToTable("EnsembleSignals");
                });

            modelBuilder.Entity("TradingAssistant.Domain.Intelligence.FeatureSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FeatureCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FeatureVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FeaturesHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("FeaturesJson")
                        .IsRequired()
                        .HasMaxLength(32000)
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OutcomeUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TradeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TradeOutcome")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TradePnlPercent")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TradeId")
                        .IsUnique();

                    b.HasIndex("TradeOutcome");

                    b.HasIndex("Symbol", "CapturedAt");

                    b.ToTable("FeatureSnapshots");
                });

            modelBuilder.Entity("TradingAssistant.Domain.Intelligence.MarketProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("DnaProfileJson")
                        .IsRequired()
                        .HasMaxLength(16000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DnaProfileUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VixSymbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MarketCode")
                        .IsUnique();

                    b.ToTable("MarketProfiles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            ConfigJson = "{\"tradingHours\":{\"open\":\"09:30\",\"close\":\"16:00\"},\"regimeThresholds\":{\"highVol\":30,\"bullBreadth\":0.60,\"bearBreadth\":0.40}}",
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            DataSource = "yahoo",
                            DnaProfileJson = "{}",
                            Exchange = "NYSE/NASDAQ",
                            IsActive = true,
                            MarketCode = "US_SP500",
                            Timezone = "America/New_York",
                            VixSymbol = "^VIX"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            ConfigJson = "{\"tradingHours\":{\"open\":\"09:15\",\"close\":\"15:30\"},\"regimeThresholds\":{\"highVol\":25,\"bullBreadth\":0.55,\"bearBreadth\":0.45}}",
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "INR",
                            DataSource = "yahoo",
                            DnaProfileJson = "{}",
                            Exchange = "NSE",
                            IsActive = true,
                            MarketCode = "IN_NIFTY50",
                            Timezone = "Asia/Kolkata",
                            VixSymbol = "^INDIAVIX"
                        });
                });

            modelBuilder.Entity("TradingAssistant.Domain.Intelligence.MarketRegime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AdvanceDeclineRatio")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BreadthScore")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ClassifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ConfidenceScore")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentRegime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PctAbove200Sma")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("RegimeDuration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegimeStartDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SmaSlope200")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SmaSlope50")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VixLevel")
                        .HasPrecision(8, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClassifiedAt");

                    b.HasIndex("MarketCode");

                    b.ToTable("MarketRegimes");
                });

            modelBuilder.Entity("TradingAssistant.Domain.Intelligence.MistakePatternReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaudeAnalysis")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LosingTradeCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("MistakeBreakdownJson")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("MostCommonMistake")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecommendationsJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegimeBreakdownJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("TradeCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnalyzedAt");

                    b.HasIndex("MarketCode");

                    b.ToTable("MistakePatternReports");
                });

            modelBuilder.Entity("TradingAssistant.Domain.Intelligence.MlModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Accuracy")
                        .HasColumnType("REAL");

                    b.Property<double>("Auc")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeactivationReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double>("F1Score")
                        .HasColumnType("REAL");

                    b.Property<string>("FeatureImportanceJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("FeatureVersion")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LossSamples")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ModelVersion")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Precision")
                        .HasColumnType("REAL");

                    b.Property<double>("Recall")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("TrainedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TrainingSamples")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ValidationSamples")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WinSamples")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MarketCode", "IsActive");

                    b.HasIndex("MarketCode", "ModelVersion")
                        .IsUnique();

                    b.ToTable("MlModels");
                });

            modelBuilder.Entity("TradingAssistant.Domain.Intelligence.MonthlyAttribution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Alpha")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BenchmarkReturn")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Beta")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BetaContribution")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("RegimeContribution")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("RegimeAlignedTrades")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RegimeMismatchedTrades")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Residual")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalReturn")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("TradeCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MarketCode", "Year", "Month")
                        .IsUnique();

                    b.ToTable("MonthlyAttributions");
                });

            modelBuilder.Entity("TradingAssistant.Domain.Intelligence.PipelineRunLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RunDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("StepOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MarketCode", "RunDate");

                    b.ToTable("PipelineRunLogs");
                });

            modelBuilder.Entity("TradingAssistant.Domain.Intelligence.RegimeTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BreadthScore")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FromRegime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PctAbove200Sma")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SmaSlope200")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SmaSlope50")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<int>("ToRegime")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TransitionDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VixLevel")
                        .HasPrecision(8, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MarketCode");

                    b.HasIndex("TransitionDate");

                    b.ToTable("RegimeTransitions");
                });

            modelBuilder.Entity("TradingAssistant.Domain.Intelligence.RuleDiscovery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscoveredRulesJson")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LosingTrades")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("PatternsJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StrategyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("TradeCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("WinningTrades")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MarketCode");

                    b.HasIndex("StrategyId");

                    b.ToTable("RuleDiscoveries");
                });

            modelBuilder.Entity("TradingAssistant.Domain.Intelligence.StrategyAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AllocationPercent")
                        .HasPrecision(8, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("Regime")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StrategyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SwitchoverStartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MarketCode")
                        .IsUnique();

                    b.ToTable("StrategyAssignments");
                });

            modelBuilder.Entity("TradingAssistant.Domain.Intelligence.StrategyAutopsy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketConditionImpact")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaxDrawdownPercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MonthlyReturnPercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("PrimaryLossReason")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecommendationsJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RootCausesJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SharpeRatio")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShouldRetire")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StrategyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("TradeCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WinRate")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId");

                    b.HasIndex("MarketCode", "PeriodStart");

                    b.ToTable("StrategyAutopsies");
                });

            modelBuilder.Entity("TradingAssistant.Domain.Intelligence.StrategyDecayAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AlertedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("AlertType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaudeAnalysis")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HistoricalSharpe")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rolling30DayAvgPnl")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rolling30DaySharpe")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rolling30DayWinRate")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rolling60DayAvgPnl")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rolling60DaySharpe")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rolling60DayWinRate")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rolling90DayAvgPnl")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rolling90DaySharpe")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rolling90DayWinRate")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StrategyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggerReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MarketCode");

                    b.HasIndex("StrategyId");

                    b.HasIndex("AlertType", "IsResolved");

                    b.ToTable("StrategyDecayAlerts");
                });

            modelBuilder.Entity("TradingAssistant.Domain.Intelligence.StrategyRegimeScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("Regime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SampleSize")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SharpeRatio")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StrategyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId", "MarketCode", "Regime")
                        .IsUnique();

                    b.ToTable("StrategyRegimeScores");
                });

            modelBuilder.Entity("TradingAssistant.Domain.Intelligence.TournamentEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AllocationPercent")
                        .HasPrecision(8, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DaysActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EquityCurveJson")
                        .IsRequired()
                        .HasMaxLength(16000)
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaxDrawdown")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PaperAccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PromotedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RetiredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RetirementReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SharpeRatio")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StrategyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalReturn")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalTrades")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TournamentRunId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WinRate")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId");

                    b.HasIndex("TournamentRunId");

                    b.HasIndex("Status", "MarketCode");

                    b.ToTable("TournamentEntries");
                });

            modelBuilder.Entity("TradingAssistant.Domain.Intelligence.TournamentRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("EntryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxEntries")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MarketCode", "Status");

                    b.ToTable("TournamentRuns");
                });

            modelBuilder.Entity("TradingAssistant.Domain.Intelligence.TradeReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("DurationHours")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EntryPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExitDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Grade")
                        .HasPrecision(8, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("IndicatorValuesJson")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("LessonsLearnedJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MistakeType")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("MlConfidence")
                        .HasColumnType("REAL");

                    b.Property<int>("OutcomeClass")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PnlAbsolute")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PnlPercent")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegimeAtEntry")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegimeAtExit")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StrategyName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("StrengthsJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TradeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WeaknessesJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MarketCode");

                    b.HasIndex("OutcomeClass");

                    b.HasIndex("TradeId")
                        .IsUnique();

                    b.HasIndex("Symbol", "ReviewedAt");

                    b.ToTable("TradeReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
