namespace TradingAssistant.Contracts.DTOs;

public record BacktestResultDto(
    Guid Id,
    Guid BacktestRunId,
    Guid StrategyId,
    string Symbol,
    string Status,
    int TotalTrades,
    decimal WinRate,
    decimal TotalReturn,
    decimal MaxDrawdown,
    decimal SharpeRatio,
    DateTime StartDate,
    DateTime EndDate,
    DateTime CreatedAt,
    // Extended metrics
    decimal Cagr = 0,
    decimal SortinoRatio = 0,
    decimal CalmarRatio = 0,
    decimal ProfitFactor = 0,
    decimal Expectancy = 0,
    decimal? OverfittingScore = null,
    string? EquityCurveJson = null,
    string? TradeLogJson = null,
    string? MonthlyReturnsJson = null,
    string? BenchmarkReturnJson = null,
    string? ParametersJson = null,
    string? WalkForwardJson = null,
    string? SpyComparisonJson = null,
    // Portfolio-specific fields (nullable for single-symbol)
    Guid? UniverseId = null,
    string? UniverseName = null,
    decimal InitialCapital = 100_000m,
    int MaxPositions = 10,
    int? TotalSymbols = null,
    int? SymbolsWithData = null,
    int? UniqueSymbolsTraded = null,
    decimal? AveragePositionsHeld = null,
    int? MaxPositionsHeld = null,
    string? SymbolBreakdownJson = null,
    string? ExecutionLogJson = null,
    string? RegimeTimelineJson = null);
