// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingAssistant.Infrastructure.Persistence;

#nullable disable

namespace TradingAssistant.Infrastructure.Migrations.Intelligence
{
    [DbContext(typeof(IntelligenceDbContext))]
    [Migration("20260302200000_InitialIntelligence")]
    partial class InitialIntelligence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("TradingAssistant.Domain.Intelligence.BreadthSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AdvanceDeclineRatio")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("Advancing")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Declining")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("NewHighs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NewLows")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PctAbove200Sma")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PctAbove50Sma")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalStocks")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MarketCode", "SnapshotDate");

                    b.ToTable("BreadthSnapshots");
                });

            modelBuilder.Entity("TradingAssistant.Domain.Intelligence.CorrelationSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LookbackDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatrixJson")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotDate");

                    b.ToTable("CorrelationSnapshots");
                });

            modelBuilder.Entity("TradingAssistant.Domain.Intelligence.CostProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CommissionPerShare")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CommissionPercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExchangeFeePercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SpreadEstimatePercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxPercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MarketCode", "IsActive");

                    b.ToTable("CostProfiles");
                });

            modelBuilder.Entity("TradingAssistant.Domain.Intelligence.MarketProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("DnaProfileJson")
                        .IsRequired()
                        .HasMaxLength(16000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DnaProfileUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VixSymbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MarketCode")
                        .IsUnique();

                    b.ToTable("MarketProfiles");
                });

            modelBuilder.Entity("TradingAssistant.Domain.Intelligence.MarketRegime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AdvanceDeclineRatio")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BreadthScore")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ClassifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ConfidenceScore")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentRegime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PctAbove200Sma")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("RegimeDuration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegimeStartDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SmaSlope200")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SmaSlope50")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VixLevel")
                        .HasPrecision(8, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClassifiedAt");

                    b.HasIndex("MarketCode");

                    b.ToTable("MarketRegimes");
                });

            modelBuilder.Entity("TradingAssistant.Domain.Intelligence.PipelineRunLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RunDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("StepOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MarketCode", "RunDate");

                    b.ToTable("PipelineRunLogs");
                });

            modelBuilder.Entity("TradingAssistant.Domain.Intelligence.RegimeTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BreadthScore")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FromRegime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PctAbove200Sma")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SmaSlope200")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SmaSlope50")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<int>("ToRegime")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TransitionDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VixLevel")
                        .HasPrecision(8, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MarketCode");

                    b.HasIndex("TransitionDate");

                    b.ToTable("RegimeTransitions");
                });
#pragma warning restore 612, 618
        }
    }
}
